import { Router } from 'express';
import { authRoutes } from './auth.routes';
import { productionOrderRoutes } from './productionOrder.routes';
import { preparationRoutes } from './preparation.routes';
import { stageRoutes } from './stage.routes';
import { boxRoutes } from './box.routes';
import { laboratoryRoutes } from './laboratory.routes';
import { pesagemRoutes } from './pesagem.routes';
import { adminRoutes } from './admin.routes';
import { pcpRoutes } from './pcp.routes';
import { dashboardRoutes } from './dashboard.routes';
import { listaSaidaRoutes } from './listaSaida.routes';
import { fabricQualityRoutes } from './fabricQuality.routes';
import { configRoutes } from './config.routes';
import { globalRateLimiter } from '../middlewares/rateLimiter.middleware';

const router = Router();
router.use(globalRateLimiter);
router.use('/auth', authRoutes);
router.use('/production-orders', productionOrderRoutes);
router.use('/preparation', preparationRoutes);
router.use('/stage', stageRoutes);
router.use('/box', boxRoutes);
router.use('/laboratory', laboratoryRoutes);
router.use('/pesagem', pesagemRoutes);
router.use('/admin', adminRoutes);
router.use('/pcp', pcpRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/lista-saida', listaSaidaRoutes);
router.use('/fabric-quality', fabricQualityRoutes);
router.use('/config', configRoutes);
export { router };
